apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  qotm_mapping
      prefix: /skmnist/prediction/
      service: ie-sidecar:9001
  creationTimestamp: null
  name: ie-sidecar
  selfLink: /api/v1/namespaces/kubeflow-seldon/services/ie-sidecar
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    seldon-app: mnist-classifier
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
