apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: mnist-classifier
spec:
  destination:
    name: mnist-classifier
  precedence: 1
  route:
  - labels:
      version: sk1
  - weight: 100