apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  seldon_mnist-classifier_rest_mapping
      prefix: /seldon/mnist-classifier/
      service: mnist-classifier:8000
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  mnist-classifier_grpc_mapping
      grpc: true
      prefix: /seldon.protos.Seldon/
      rewrite: /seldon.protos.Seldon/
      headers:
        seldon: mnist-classifier
      service: mnist-classifier:5001
  creationTimestamp: null
  labels:
    seldon-app: mnist-classifier
    seldon-deployment-id: mnist-classifier
  name: mnist-classifier
  ownerReferences:
  - apiVersion: machinelearning.seldon.io/v1alpha1
    controller: true
    kind: SeldonDeployment
    name: mnist-classifier
    uid: fea5a5a5-5858-11e8-ba22-42010a8001a0
  selfLink: /api/v1/namespaces/kubeflow-seldon/services/mnist-classifier
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: grpc
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    seldon-app: mnist-classifier
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
