apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  seldon_mnist-classifier-sk_rest_mapping
      prefix: /seldon/mnist-classifier/
      service: mnist-classifier:8000
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  mnist-classifier-sk_grpc_mapping
      grpc: true
      prefix: /seldon.protos.Seldon/
      rewrite: /seldon.protos.Seldon/
      headers:
        seldon: mnist-classifier
      service: mnist-classifier:5001
  creationTimestamp: null
  labels:
    seldon-app: mnist-classifier
    seldon-deployment-id: mnist-classifier
  name: mnist-classifier

spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: grpc
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    model: mnist
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
