apiVersion: 0.1.0
environments:
  cloud:
    destination:
      namespace: kubeflow-seldon
      server: https://35.196.248.40
    k8sVersion: v1.7.0
    path: cloud
  default:
    destination:
      namespace: default
      server: https://35.196.248.40
    k8sVersion: v1.8.0
    path: default
kind: ksonnet.io/app
libraries:
  argo:
    gitVersion:
      commitSha: 2cdd735c68eb813bb2f3e086dc98651335649c14
      refSpec: master
    name: argo
    registry: kubeflow
  core:
    gitVersion:
      commitSha: 2cdd735c68eb813bb2f3e086dc98651335649c14
      refSpec: master
    name: core
    registry: kubeflow
  seldon:
    gitVersion:
      commitSha: 2cdd735c68eb813bb2f3e086dc98651335649c14
      refSpec: master
    name: seldon
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: 2cdd735c68eb813bb2f3e086dc98651335649c14
      refSpec: master
    name: tf-job
    registry: kubeflow
name: ks_kubeflow_seldon
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: 2cdd735c68eb813bb2f3e086dc98651335649c14
      refSpec: master
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/master/kubeflow
version: 0.0.1
