apiVersion: machinelearning.seldon.io/v1alpha1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
    seldon-app: mnist-classifier
    prediction-version: sk
  name: mnist-classifier-sk
spec:
  annotations:
    deployment_version: v1
    project_name: MNIST Example
  name: mnist-classifier
  predictors:
  - annotations:
      predictor_version: v1
    componentSpec:
      spec:
        containers:
        - image: smolina74/skmnistclassifier_runtime:0.83
          imagePullPolicy: Always
          name: sk-model
          volumeMounts:
          - mountPath: "/data"
            name: persistent-storage

        - image: smolina74/skmnistclassifier_output_tx_runtime:0.83"
          imagePullPolicy: "Always"
          name: "mnist-classifier-sk-output-tx"
          volumeMounts:
          - mountPath: "/data"
            name: persistent-storage
            
        terminationGracePeriodSeconds: 1
        volumes:
        - name: persistent-storage
          volumeSource:
            persistentVolumeClaim:
              claimName: nfs-1
    graph: 
      children: 
      - endpoint:
          type: "REST"
        name: "mnist-classifier-sk-output-tx"
        type: "TRANSFORMER"
      endpoint: 
        type: "REST"
      name: "mnist-classifier-sk"
      type: "MODEL"
      
    name: mnist-classifier-sk
    replicas: 1
